# Generated by Django 5.1.6 on 2025-05-07 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unievent_event_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventregistration',
            options={'permissions': [('can_register_event', 'Can register for events')]},
        ),
    ]
